export default [
    [{
        headlineOfQuestion: "Скільки  в javaScript типів примітивів ?",
        answer1: "2",
        answer2: "3",
        answer3: "6",
        answer4: "5",
        rightAnswer: '4',
    },
    {
        headlineOfQuestion: "Що таке масив?",
        answer1: "функція",
        answer2: " колекція з проіндексованими значеннями",
        answer3: "об'єкт",
        answer4: "область видимості",
        rightAnswer: '2',
    },
    {
        headlineOfQuestion: "У чому відмінність між локальної та глобальної змінної?",
        answer1: "Локальні помітні всюди, глобальні тільки у функціях",
        answer2: "Локальні можна перевизначати, глобальні не можна",
        answer3: "Глобальні помітні всюди, локальні тільки у функціях",
        answer4: "відмінностей немає",
        rightAnswer: '3',
    },
    {
        headlineOfQuestion: "Індексація масиву починається з ",
        answer1: "0",
        answer2: "1",
        answer3: "2",
        answer4: "-1",
        rightAnswer: '1',
    },
    {
        headlineOfQuestion: "Ключі властивостей це завжди...",
        answer1: "число",
        answer2: "рядок",
        answer3: "буль",
        answer4: "довільний тип",
        rightAnswer: '2',
    },
    {
        headlineOfQuestion: "Який цикл використовується для перебору властивостей об'єкта?",
        answer1: "for...each",
        answer2: "for...off",
        answer3: "for...in",
        answer4: "for...out",
        rightAnswer: '3',
    },
    {
        headlineOfQuestion: "Які аргументи приймає метод apply ()?",
        answer1: "Об'єкт і список аргументів для функції",
        answer2: "Об'єкт і масив аргументів для функції",
        answer3: "Список аргументів для функції",
        answer4: "Об'єкт",
        rightAnswer: '2',
    },
    {
        headlineOfQuestion: "Значення якої змінної не можна змінити після її оголошення?",
        answer1: "const",
        answer2: "let",
        answer3: "var",
        answer4: "constanta",
        rightAnswer: '1',
    },
    {
        headlineOfQuestion: "Який call метод приймає в якості аргументів?",
        answer1: "об'єкт",
        answer2: "список аргументів для функції",
        answer3: "об'єкт і масив аргуменів для функції",
        answer4: "об'єкт і список аргументів для функції",
        rightAnswer: '4',
    },
    {
        headlineOfQuestion: "Що таке arguments в тілі функції?",
        answer1: "Локальна змінна містить псевдомасив аргументів",
        answer2: "Локальна змінна містить псевдомасив параметрів",
        answer3: "Локальна змінна містить масив параметрів",
        answer4: "Локальна змінна містить масив аргументів",
        rightAnswer: '1',
    },
    ],
    [{
        headlineOfQuestion: "Яка властивість задає відступ для елемента?",
        answer1: "padding",
        answer2: "border",
        answer3: "margin",
        answer4: "width",
        rightAnswer: '3',
    },
    {
        headlineOfQuestion: "Виберіть значення rgb, яке відповідає зеленому кольору",
        answer1: "rgb(0,255,0)",
        answer2: "rgb(0,0,255)",
        answer3: "rgb(255,0,0)",
        answer4: "rgb(255,0,255)",
        rightAnswer: '1',
    },
    {
        headlineOfQuestion: "Що робить flex-wrap..",
        answer1: "задає перенесення елементів вздовж допоміжної осі",
        answer2: "задає перенесення елементів вздовж головної осі",
        answer3: "задає напрямок головної осі",
        answer4: "задає правило вирівнювання елементів вздовж головної осі",
        rightAnswer: '2',
    },
    {
        headlineOfQuestion: "Що змінює правила розрахунку розмірів content-area?",
        answer1: "display: inline-block",
        answer2: "display: block",
        answer3: "box-sizing: content-box/border-box",
        answer4: "display: inline",
        rightAnswer: '3',
    },
    {
        headlineOfQuestion: "Скільки осей є у flex контейнері?",
        answer1: "1",
        answer2: "3",
        answer3: "2",
        answer4: "у flex контейнері немає осей",
        rightAnswer: '3',
    },
    {
        headlineOfQuestion: "Який із типів селекторів має найбільший пріоритет?",
        answer1: "тег",
        answer2: "ідентифікатор",
        answer3: "клас",
        answer4: "селектор атрибута",
        rightAnswer: '2',
    },
    {
        headlineOfQuestion: "Властивість position:relative змістить сусідній елемент при значенні властивості",
        answer1: "top: 50px;",
        answer2: "left: 50px;",
        answer3: "bottom: 50px;",
        answer4: "margin: 50px;",
        rightAnswer: '4',
    },
    {
        headlineOfQuestion: "Яке значення властивості transform відповідає за поворот елемента?",
        answer1: "scale",
        answer2: "rotate",
        answer3: "skew",
        answer4: "translate",
        rightAnswer: '2',
    },
    {
        headlineOfQuestion: "Виберіть правильне значення властивоті color",
        answer1: "#25fh17;",
        answer2: "rgba(250,50,1,37%);",
        answer3: "#110000",
        answer4: "hsla(100%,50%,25%,.1);",
        rightAnswer: '3',
    },
    {
        headlineOfQuestion: "Властивість position:fixed застосовують для",
        answer1: "створення випадаючого меню",
        answer2: "навігації всередині заданого блоку сторінки",
        answer3: "створення блоку, закріпленого у viewport",
        answer4: "навігації між сторінками",
        rightAnswer: '3',
    },
    ],
    [{
        headlineOfQuestion: "Яке з наступних тверджень вірно для класу: java.util.ArrayList?",
        answer1: "Елементи в колекції доступні за допомогою унікального ключа",
        answer2: "Колекція гарантовано незмінна (immutable)",
        answer3: "Елементи колекції гарантовано унікальні",
        answer4: "Елементи в колекції впорядковані",
        rightAnswer: '4',
    },
    {
        headlineOfQuestion: "Яке з наступних тверджень вірно для method-local inner class?",
        answer1: "Може бути оголошений як public",
        answer2: "Може бути оголошений як finalabstract",
        answer3: "Може бути оголошений як static",
        answer4: "Має бути оголошено як final",
        rightAnswer: '2',
    },
    {
        headlineOfQuestion: "Яке з наступних тверджень вірно?",
        answer1: "Відповідний спосіб для перехоплення assertion failure буде через catch clause",
        answer2: "У assert statement, вираз після (:) може бути довільним виразом Java.",
        answer3: "У assert statement, якщо вираз після двокрапка (:) немає значення, assert's error message буде порожнім.",
        answer4: "Якщо switch блоку немає default, вважається придатним додавання assert default.",
        rightAnswer: '4',
    },
    {
        headlineOfQuestion: "Де правильно створена проста змінна?",
        answer1: "byte x = 100000;",
        answer2: "float x = 23.3f;",
        answer3: "char str = 'ab';",
        answer4: "int[] a;",
        rightAnswer: '2',
    },
    {
        headlineOfQuestion: "Де правильно створений масив?",
        answer1: "int[] a = new int[] {1, 2, 3, 4, 5};",
        answer2: "int a = new int[] {1, 2, 3, 4, 5};",
        answer3: "int a[] = 1, 2, 3, 4, 5;",
        answer4: "int[] a = int[] {1, 2, 3, 4, 5};",
        rightAnswer: '1',
    },
    {
        headlineOfQuestion: "Який метод дозволяє запустити програму на Java?",
        answer1: "Будь-який, його можна ставити в налаштуваннях проекту",
        answer2: "Запуск програми відбувається через компіляцію проекту, основного методу немає",
        answer3: "З класу, що був написаний першим і з методів що є всередині нього",
        answer4: "З методу main в будь-якому з класів",
        rightAnswer: '4',
    },
    {
        headlineOfQuestion: "Скільки параметрів може приймати функція?",
        answer1: "Не більше 3",
        answer2: "Не більше 10",
        answer3: "Не більше 5",
        answer4: "Необмежена кількість",
        rightAnswer: '4',
    },
    {
        headlineOfQuestion: "Що спільного у всіх елементів масиву?",
        answer1: "їх назви",
        answer2: "їх розмір",
        answer3: "Їх адреса в пам'яті",
        answer4: "Їх тип даних",
        rightAnswer: '4',
    },
    {
        headlineOfQuestion: "Де правильно присвоєно нове значення до багатовимірного масиву?",
        answer1: "a{0}{0} = 1;",
        answer2: "a[0, 0] = 1;",
        answer3: "a[0][0] = 1;",
        answer4: "a(0)(0) = 1;",
        rightAnswer: '3',
    },
    {
        headlineOfQuestion: "що поверне метод, оголошений наступним чином: public static int getAmount()",
        answer1: "Не зрозуміло, треба дивитися код методу",
        answer2: "Поверне цілочисельне значення",
        answer3: "Поверне посилання на об'єкт класа this",
        answer4: "Поверне static-поле класа",
        rightAnswer: '2',
    },
    ],
    [{
        headlineOfQuestion: "Де правильно створена змінна?",
        answer1: "int num = 2",
        answer2: "num = float(2)",
        answer3: "$num = 2",
        answer4: "var num = 2",
        rightAnswer: '2',
    },
    {
        headlineOfQuestion: "Як отримати дані від користувача?",
        answer1: "Використати метод input()",
        answer2: "Використати метод readLine()",
        answer3: "Використати метод cin()",
        answer4: "Використати метод get()",
        rightAnswer: '1',
    },
    {
        headlineOfQuestion: "Яка бібліотека відповідає за час?",
        answer1: "Time",
        answer2: "clock",
        answer3: "localtime",
        answer4: "time",
        rightAnswer: '4',
    },
    {
        headlineOfQuestion: "Яка функція виводить що-небудь в консоль?",
        answer1: "write();",
        answer2: "log();",
        answer3: "out();",
        answer4: "print();",
        rightAnswer: '4',
    },
    {
        headlineOfQuestion: "Виберіть правильну запис оператора присвоювання:",
        answer1: "10 = х",
        answer2: "у = 7,8",
        answer3: "а = 5",
        answer4: "а == b + x",
        rightAnswer: '3',
    },
    {
        headlineOfQuestion: "Вкажіть оператор введення",
        answer1: "input ()",
        answer2: "print ()",
        answer3: "int ()",
        answer4: "random ()",
        rightAnswer: '1',
    },
    {
        headlineOfQuestion: "Що краще використовувати для множинного розгалуження?",
        answer1: "if - elif -else",
        answer2: "Багато if",
        answer3: "if - else - elif",
        answer4: "while",
        rightAnswer: '1',
    },
    {
        headlineOfQuestion: "Що робить функція len ()?",
        answer1: "Повертає випадкове число",
        answer2: "Повертає довжину рядка",
        answer3: "Повертає номер символу",
        answer4: "Повертає модуль числа",
        rightAnswer: '2',
    },
    {
        headlineOfQuestion: "Від чого мова програмування називається «Пайтон»?",
        answer1: "На честь змії",
        answer2: "На честь ТВ-шоу ",
        answer3: "На честь гри",
        answer4: "На честь страви",
        rightAnswer: '2',
    },
    {
        headlineOfQuestion: "а = 345. Що виведе команда print (// 100)",
        answer1: "34",
        answer2: "5",
        answer3: "4",
        answer4: "3",
        rightAnswer: '4',
    },
    ],
];